import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "fr": {
          '1': 'Que souhaitez-vous commander?',
          '2': 'Produits populaires',
          '3': 'Magasins populaires',
          '4': 'voir tout',
          '5':
              'Veuillez activer la localisation de votre téléphone pour une livraison précise à votre adresse.',
          '6': 'Vous commandez en deux clics',
          '8': 'Profitez de nos réductions exclusives et offres spéciales',
          '7': 'Réductions, Offres spéciales',
          '10': 'Découvrez une délicieuse variété de plats pour tous les goûts',
          '9': 'Nourriture délicieuse',
          '12': 'Service de livraison rapide et fiable pour vos colis',
          '11': 'Livraison de colis fiable',
          '13': 'Que souhaitez-vous envoyer ?',
          '14': 'Entrez les détails du colis',
          '15': "D'où ?",
          '16': 'Choisissez le lieu de ramassage',
          '17': 'Lieu de ramassage exact',
          '18': 'Entrez les détails sur le lieu de ramassage exact',
          '19': 'Où ?',
          '20': 'Lieu de dépôt exact',
          '21': 'Entrez les détails sur le lieu de dépôt exact',
          '22': 'Dès que possible',
          '23': 'Choisissez un jour et une heure',
          '24': 'Numéro du destinataire',
          '25': 'Vous devez mettre le numéro de téléphone reçu',
          '26': 'pour confirmer la commande.',
          '27': 'Facture',
          '28': 'Prix de livraison estimé :',
          '29': 'Service de nuit* :',
          '30': 'PRIX TOTAL :'
        },
        "en": {
          '1': 'what would you like to order?',
          '2': 'Popular products',
          '3': 'Popular stores',
          '4': 'view all',
          '5':
              "Please enable your phone's location for accurate delivery to your address.",
          '6': 'You order in two clicks',
          '8': 'Promotions',
          '7': 'Discounts, Special Offers',
          '10': 'Everything',
          '9': 'Delicious and fresh food',
          '12': 'Courier',
          '11': 'Reliable package delivery',
          '13': 'What do you want to send?',
          '14': 'Enter details about the package',
          '15': 'Where from?',
          '16': 'Pick Pickup Location',
          '17': 'Exact Pickup Location',
          '18': 'Enter details about exact Pickup Location',
          '19': 'Where to?',
          '20': 'Exact Drop-off Location',
          '21': 'Enter details about the exact drop-off location',
          '22': 'As Soon As Possible',
          '23': 'Choose a Day and Time',
          '24': 'Recipient number',
          '25': 'You should put the received phone number',
          '26': 'to confirm the order.',
          '27': 'Invoice',
          '28': 'Estimated Delivery Price:',
          '29': 'Night Service*:',
          '30': 'TOTAL PRICE:'
        },
        "ar": {
          '1': 'ماذا ترغب في طلبه؟',
          '2': 'المنتجات الشائعة',
          '3': 'المتاجر الشائعة',
          '4': 'عرض الكل',
          '5': "يرجى تفعيل موقع هاتفك للتوصيل الدقيق إلى عنوانك.",
          '6': 'تقوم بالطلب بنقراتين',
          '8': 'عروض ترويجية',
          '7': 'عروض خاصة ,خصومات',
          '10': 'كل شيء',
          '9': '  طعام لذيذ وطازج ',
          '12': 'موصل',
          '11': 'توصيل طرد موثوق',
          '13': 'ماذا تريد أن ترسل؟',
          '14': 'أدخل تفاصيل الطرد',
          '15': 'من أين؟',
          '16': 'اختر موقع الاستلام',
          '17': 'موقع الاستلام الدقيق',
          '18': 'أدخل تفاصيل موقع الاستلام الدقيق',
          '19': 'إلى أين؟',
          '20': 'موقع التسليم الدقيق',
          '21': 'أدخل تفاصيل موقع التسليم الدقيق',
          '22': 'في أقرب وقت ممكن',
          '23': 'اختر يومًا ووقتًا',
          '24': 'رقم المستلم',
          '25': 'يجب عليك وضع رقم الهاتف المستلم',
          '26': 'لتأكيد الطلب.',
          '27': 'فاتورة',
          '28': 'سعر التوصيل المقدر :',
          '29': 'خدمة ليلية* :',
          '30': 'السعر الإجمالي :'
        }
      };
}
