workflows:
  ios-spooding-express:
    name: iOS Build & Publish - Spooding Express
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      vars:
        APPLE_ID: "wseize@gmail.com"                 
        APP_SPECIFIC_PASSWORD: "ssaa-qfwm-yupg-matu" 
        IOS_TEAM_ID: "9A1BC23D45"                    
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.spooding.express"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Clean previous build
        script: |
          flutter clean
      - name: Build iOS App (Release)
        script: |
          flutter build ios --release --no-codesign

    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
        submit_to_testflight: true
        submit_to_app_store: true
