workflows:
  flutter-ios-build:
    name: Flutter iOS Build & Publish
    instance_type: mac_mini_m2
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter test
      - flutter build ipa --release --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    integrations:
      app_store_connect: "Express"   # اسم الـ integration اللي ضفتو في Codemagic
    publishing:
      app_store_connect:
        auth: integration
        app: com.spooding.express
        skip_screenshots: true
        skip_metadata: true
