workflows:
  ios-spooding-express:
    name: iOS Build - SpooDing Express
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      vars:
        APPLE_ID: "wseize@gmail.com"                 # Apple ID متاعك
        APP_SPECIFIC_PASSWORD: "ssaa-qfwm-yupg-matu" # App-specific password
        IOS_TEAM_ID: "9A1BC23D45"                    # Team ID متاعك (من Membership page)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.spooding.express"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Clean previous build
        script: |
          flutter clean
      - name: Build iOS App (Release)
        script: |
          flutter build ios --release --no-codesign
